server:
  port: 8081

spring:
  application:
    name: user-service
  datasource:
    url: ${USER_SERVICE_DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${USER_SERVICE_DB_USERNAME}
    password: ${USER_SERVICE_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance-id: ${spring.application.name}:${server.port}
