spring:
  application:
    name: api-gateway

server:
  port: 8882

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance-id: ${spring.application.name}:${server.port}




