spring:
  application:
    name: user-service
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      import-check:
        enabled: true
server:
  port: 8082
  config:
    import: optional:file:.env[.properties]


  servlet:
    context-path: /api/v1x


management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
