---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: microservices-config
  namespace: microservices
  labels:
    app: microservices

data:
  CONFIG_SERVER_URL: "http://config-server:8888"
  DISCOVERY_SERVER_URL: "http://service-discovery:8761/eureka/"
---
apiVersion: v1
kind: Secret
metadata:
  name: microservices-secrets
  namespace: microservices
  labels:
    app: microservices

type: Opaque
stringData:
  DB_USERNAME: "mawuli"
  DB_PASSWORD: "mawuli302"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-discovery
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-discovery
  template:
    metadata:
      labels:
        app: service-discovery
    spec:
      containers:
        - name: service-discovery
          image: mawulidev/service-discovery:latest
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: service-discovery
  namespace: microservices
spec:
  selector:
    app: service-discovery
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: mawulidev/config-server:latest
          ports:
            - containerPort: 8888
          env:
            - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: config-server
  namespace: microservices
spec:
  selector:
    app: config-server
  ports:
    - protocol: TCP
      port: 8888
      targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog-service
  template:
    metadata:
      labels:
        app: blog-service
    spec:
      containers:
        - name: blog-service
          image: mawulidev/blog-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA.CLIENT.SERVICEURL.DEFAULTZONE
              value: "http://service-discovery:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service
  namespace: microservices
spec:
  selector:
    app: blog-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-service-postgres
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-service-postgres
  template:
    metadata:
      labels:
        app: blog-service-postgres
    spec:
      containers:
        - name: blog-service-postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "blog-service-database"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: DB_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: microservices-secrets
                  key: DB_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: blog-service-postgres
  namespace: microservices
spec:
  selector:
    app: blog-service-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
